package yunxiao

import (
	"github.com/mark3labs/mcp-go/mcp"

	"github.com/futuretea/yunxiao-mcp-server/pkg/toolset"
)

func projexInsightTools() []toolset.ServerTool {
	return []toolset.ServerTool{
		{
			Tool: mcp.NewTool("get_project_risk_dashboard",
				mcp.WithDescription("Get a read-only project risk dashboard with category samples, overdue work items, and optional high-priority/stale sections. Best used for project health checks and sprint retrospectives."),
				mcp.WithString("organizationId", mcp.Description("Yunxiao organization ID. When omitted, the server uses the user's default organization.")),
				mcp.WithString("projectId", mcp.Required(), mcp.Description("Project ID. Use search_projects to discover valid IDs.")),
				mcp.WithString("categories", mcp.Description("Comma-separated categories for category totals. Defaults to Risk,Bug,Task.")),
				mcp.WithString("subject", mcp.Description("Subject contains filter applied to every section.")),
				mcp.WithString("status", mcp.Description("Comma-separated active status IDs applied to every section.")),
				mcp.WithString("statusStage", mcp.Description("Comma-separated status stage IDs applied to every section.")),
				mcp.WithString("assignedTo", mcp.Description("Comma-separated assignee user IDs applied to every section.")),
				mcp.WithString("creator", mcp.Description("Comma-separated creator user IDs applied to every section.")),
				mcp.WithString("sprint", mcp.Description("Comma-separated sprint IDs applied to every section.")),
				mcp.WithString("workitemType", mcp.Description("Comma-separated work item type IDs applied to every section.")),
				mcp.WithString("tag", mcp.Description("Comma-separated tag IDs applied to every section.")),
				mcp.WithString("overdueBefore", mcp.Description("Planned finish date upper bound for overdue work items. Defaults to today.")),
				mcp.WithString("highPriority", mcp.Description("Comma-separated priority IDs for the high-priority section.")),
				mcp.WithString("staleBefore", mcp.Description("Status update date upper bound for the stale section.")),
				mcp.WithNumber("sampleLimit", mcp.Description("Samples returned per section. Defaults to 5, clamped to 0-200.")),
				mcp.WithReadOnlyHintAnnotation(true),
			),
			Handler: handleGetProjectRiskDashboard,
		},
		{
			Tool: mcp.NewTool("get_project_member_task_status",
				mcp.WithDescription("Get per-member task status for one project with assigned, overdue, and optional status-group sections. Useful for workload balancing and identifying blocked team members."),
				mcp.WithString("organizationId", mcp.Description("Yunxiao organization ID. When omitted, the server uses the user's default organization.")),
				mcp.WithString("projectId", mcp.Required(), mcp.Description("Project ID. Use search_projects to discover valid IDs.")),
				mcp.WithString("assigneeIds", mcp.Description("Comma-separated assignee user IDs. Defaults to project members up to memberLimit.")),
				mcp.WithString("categories", mcp.Description("Comma-separated work item categories. Defaults to Task,Bug.")),
				mcp.WithString("subject", mcp.Description("Subject contains filter applied to every section.")),
				mcp.WithString("status", mcp.Description("Comma-separated status IDs applied to assigned and overdue sections.")),
				mcp.WithString("statusStage", mcp.Description("Comma-separated status stage IDs applied to assigned and overdue sections.")),
				mcp.WithString("assignedTo", mcp.Description("Comma-separated assignee user IDs applied to every section.")),
				mcp.WithString("creator", mcp.Description("Comma-separated creator user IDs applied to every section.")),
				mcp.WithString("sprint", mcp.Description("Comma-separated sprint IDs applied to every section.")),
				mcp.WithString("workitemType", mcp.Description("Comma-separated work item type IDs applied to every section.")),
				mcp.WithString("tag", mcp.Description("Comma-separated tag IDs applied to every section.")),
				mcp.WithString("overdueBefore", mcp.Description("Planned finish date upper bound for overdue work items. Defaults to today.")),
				mcp.WithString("statusGroups", mcp.Description("Optional JSON object mapping group names to comma-separated status IDs.")),
				mcp.WithNumber("memberLimit", mcp.Description("Max project members to inspect when assigneeIds is omitted. Defaults to 20.")),
				mcp.WithNumber("sampleLimit", mcp.Description("Samples returned per member section. Defaults to 5, clamped to 0-200.")),
				mcp.WithReadOnlyHintAnnotation(true),
			),
			Handler: handleGetProjectMemberTaskStatus,
		},
		{
			Tool: mcp.NewTool("get_sprint_velocity",
				mcp.WithDescription("Get historical sprint velocity metrics including completion rates, work item counts, and trend analysis per sprint. Combines sprint metadata with categorized work item completion statistics. Useful for sprint planning and delivery forecasting."),
				mcp.WithString("organizationId", mcp.Description("Yunxiao organization ID. When omitted, the server uses the user's default organization.")),
				mcp.WithString("projectId", mcp.Required(), mcp.Description("Project ID. Use search_projects to discover valid IDs.")),
				mcp.WithString("categories", mcp.Description("Comma-separated work item categories for velocity calculation. Defaults to Task,Bug.")),
				mcp.WithNumber("sprintCount", mcp.Description("Number of recent sprints to analyze. Defaults to 5, max 20.")),
				mcp.WithString("sprintStatus", mcp.Description("Comma-separated sprint statuses to include. Defaults to ARCHIVED,DONE.")),
				mcp.WithReadOnlyHintAnnotation(true),
			),
			Handler: handleGetSprintVelocity,
		},
		{
			Tool: mcp.NewTool("get_workitem_status_timeline",
				mcp.WithDescription("Get detailed status change timeline for a work item including timestamps, duration in each status, and responsible users. Parses activity history to extract workflow bottlenecks. Useful for analyzing why a task is delayed."),
				mcp.WithString("organizationId", mcp.Description("Yunxiao organization ID. When omitted, the server uses the user's default organization.")),
				mcp.WithString("workitemId", mcp.Required(), mcp.Description("Work item ID (numeric string). Find it via search_workitems.")),
				mcp.WithBoolean("includeWorkitem", mcp.Description("Whether to include basic work item info. Defaults to true.")),
				mcp.WithReadOnlyHintAnnotation(true),
			),
			Handler: handleGetWorkitemStatusTimeline,
		},
		{
			Tool: mcp.NewTool("get_blocker_analysis",
				mcp.WithDescription("Get aggregated dependency blocker analysis for a project including work items that are blocked by unresolved dependencies and work items that are blocking others. Useful for identifying critical path risks and unblocking the team."),
				mcp.WithString("organizationId", mcp.Description("Yunxiao organization ID. When omitted, the server uses the user's default organization.")),
				mcp.WithString("projectId", mcp.Required(), mcp.Description("Project ID. Use search_projects to discover valid IDs.")),
				mcp.WithString("categories", mcp.Description("Comma-separated work item categories to analyze. Defaults to Task,Bug.")),
				mcp.WithNumber("sampleLimit", mcp.Description("Max work items to analyze per category. Defaults to 20, clamped to 0-200.")),
				mcp.WithReadOnlyHintAnnotation(true),
			),
			Handler: handleGetBlockerAnalysis,
		},
		{
			Tool: mcp.NewTool("get_member_workload_trend",
				mcp.WithDescription("Get workload trend analysis for project members including current task counts, status distribution, recent activity, and overdue items. Useful for capacity planning and identifying overloaded team members."),
				mcp.WithString("organizationId", mcp.Description("Yunxiao organization ID. When omitted, the server uses the user's default organization.")),
				mcp.WithString("projectId", mcp.Required(), mcp.Description("Project ID. Use search_projects to discover valid IDs.")),
				mcp.WithString("assigneeIds", mcp.Description("Comma-separated assignee user IDs. Defaults to project members up to memberLimit.")),
				mcp.WithString("categories", mcp.Description("Comma-separated work item categories. Defaults to Task,Bug.")),
				mcp.WithNumber("memberLimit", mcp.Description("Max project members to analyze when assigneeIds is omitted. Defaults to 20.")),
				mcp.WithNumber("daysBack", mcp.Description("Number of days to look back for recent activity. Defaults to 30.")),
				mcp.WithReadOnlyHintAnnotation(true),
			),
			Handler: handleGetMemberWorkloadTrend,
		},
		{
			Tool: mcp.NewTool("get_team_workload_breakdown",
				mcp.WithDescription("Get a detailed per-member workload breakdown with current active tasks, task subjects, status, labels, and creation dates. Useful for stand-ups, sprint planning, and identifying what each team member is working on right now."),
				mcp.WithString("organizationId", mcp.Description("Yunxiao organization ID. When omitted, the server uses the user's default organization.")),
				mcp.WithString("projectId", mcp.Required(), mcp.Description("Project ID. Use search_projects to discover valid IDs.")),
				mcp.WithString("assigneeIds", mcp.Description("Comma-separated assignee user IDs. Defaults to project members up to memberLimit.")),
				mcp.WithString("categories", mcp.Description("Comma-separated work item categories. Defaults to Task,Bug.")),
				mcp.WithString("status", mcp.Description("Comma-separated status IDs to include. Defaults to all active statuses (backlog,待处理,处理中,测试中,In Review,pending).")),
				mcp.WithNumber("memberLimit", mcp.Description("Max project members to inspect when assigneeIds is omitted. Defaults to 20.")),
				mcp.WithNumber("taskLimit", mcp.Description("Max tasks returned per member. Defaults to 10, clamped to 1-50.")),
				mcp.WithReadOnlyHintAnnotation(true),
			),
			Handler: handleGetTeamWorkloadBreakdown,
		},
	}
}
